### PR TITLE
StationWare Status Bars

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
Couldn't pump out a challenge but I did crawl through UI hell so take this as a substitute

Day #2 of PR-ing something to stationware

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
Screenshot?

**Comment by Just-a-Unity-Dev** [comment]
emo i won't be able to make a screenshot for like 1 entire day

**Comment by EmoGarbage404** [comment]
> emo i won't be able to make a screenshot for like 1 entire day

Rip. Ill test it when i get home ig

**Comment by Just-a-Unity-Dev** [comment]
I fucking did it

**Comment by Just-a-Unity-Dev** [comment]
image
image
image
image

**Comment by EmoGarbage404** [comment]
The visibility is kinda bad. You can merge but make an issue to add boxes like popups have.

**Comment by Just-a-Unity-Dev** [comment]
merging once tests succeed

**Pull request merged**
