### PR TITLE
MORE events

### LINKED ISSUE #159: troll orb is too deadly
## Description

it needs to be slower + last shorter
**Reproduction**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Just-a-Unity-Dev**
Closes #159 #153 and #138

### CODE REVIEW

**Comment by EmoGarbage404** [comment]
This doesn't' actually close 112. I thought there'd be a system that listens for construction events. If that's too much of a pain, then do what you did, but it isn't ideal.

**Comment by EmoGarbage404** [comment]
also i feel like the math challenge should be a single challenge which creates a math problem for the players to solve. having a bunch of static ones will mess up the challenge pool in terms of probability (plus it's kinda lame)

**Comment by Just-a-Unity-Dev** [comment]
> also i feel like the math challenge should be a single challenge which creates a math problem for the players to solve. having a bunch of static ones will mess up the challenge pool in terms of probability (plus it's kinda lame)

do you have a method of sending text to individual (or all) clients without sending the actual locale string

**Comment by EmoGarbage404** [comment]
> > also i feel like the math challenge should be a single challenge which creates a math problem for the players to solve. having a bunch of static ones will mess up the challenge pool in terms of probability (plus it's kinda lame)
> 
> do you have a method of modifying the text sent to individual (or all) clients

it could be the same question for every client, but just have it randomize the answer (c+p sayphrasemodifiersystem)

**Comment by EmoGarbage404** [comment]
also you could just put it in chat or use the overlay.

**Comment by Just-a-Unity-Dev** [comment]
i just fucking realized

**Comment by Just-a-Unity-Dev** [comment]
god i'm so sleep deprived rn

**Comment by Just-a-Unity-Dev** [comment]
> it could be the same question for every client, but just have it randomize the answer

what

**Comment by Just-a-Unity-Dev** [comment]
did most of it, merge when you approve

**Pull request merged**
